
import Koneksi.conek1;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.util.Collection;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Acer
 */
public class MenuFinance extends javax.swing.JPanel {
private String username;
private String userIdP;

HashMap<String, String> tableDataMap = new HashMap<>();
private HashMap<String, String> investor = new HashMap<>();

    /**
     * Creates new form MenuManager
     */
   

    /**
     * Creates new form MenuManager
     */
    public MenuFinance(String username, String userIdP) {
        initComponents();
        this.username = username;
         this.userIdP = userIdP;
        b_detail.setVisible(false);
         b_ajukan.setVisible(false);
           
            b_ubah.setVisible(false);
        b_selesai.setVisible(false);
        b_keluar.setVisible(false);
        b_update.setVisible(false);
        cmbinvestor.setVisible(false);
        datatable1();
                datatable2();
                  datatable3();
               loadInvestor();
              
                 
                

    }
    private void loadInvestor() {
          try {
            // Membuat statement dari koneksi
            Statement stmt = conek1.GetConnection().createStatement();
            
            // Query untuk mendapatkan ID dan nama admin
            String sql = "SELECT id_investor, Nama FROM investor";
            ResultSet rs = stmt.executeQuery(sql);
            
            // Tambahkan pilihan default ke dropdown
            cmbinvestor.addItem("- Pilih Investor -");
            
            // Tambahkan admin ke dropdown dan HashMap
            while (rs.next()) {
                String idInvestor = rs.getString("id_investor"); // ID bertipe String
                String namaInvestor = rs.getString("Nama");
                cmbinvestor.addItem(namaInvestor);         // Tambahkan nama admin ke dropdown
                investor.put(namaInvestor, idInvestor);
               
                
            }
            
            // Menutup statement
            stmt.close();
           
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal terhubung ke database: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainpane = new javax.swing.JPanel();
        data_proyek = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        b_detail = new rojerusan.RSMaterialButtonRectangle();
        txtcari = new javax.swing.JTextField();
        b_cari = new rojerusan.RSMaterialButtonRectangle();
        b_ajukan = new rojerusan.RSMaterialButtonRectangle();
        cmbinvestor = new javax.swing.JComboBox<>();
        detail_proyek = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table2 = new javax.swing.JTable();
        b_kembali = new rojerusan.RSMaterialButtonRectangle();
        b_step = new rojerusan.RSMaterialButtonRectangle();
        ajukan = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        b_tambah = new rojerusan.RSMaterialButtonRectangle();
        b_kembali2 = new rojerusan.RSMaterialButtonRectangle();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtstep = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtid2 = new javax.swing.JTextField();
        b_update = new rojerusan.RSMaterialButtonRectangle();
        detail_step = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        table3 = new javax.swing.JTable();
        b_keluar = new rojerusan.RSMaterialButtonRectangle();
        b_tambah1 = new rojerusan.RSMaterialButtonRectangle();
        b_ubah = new rojerusan.RSMaterialButtonRectangle();
        b_selesai = new rojerusan.RSMaterialButtonRectangle();

        setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 0, 0, new java.awt.Color(42, 37, 98)));
        setLayout(new java.awt.CardLayout());

        mainpane.setBackground(new java.awt.Color(255, 255, 255));
        mainpane.setLayout(new java.awt.CardLayout());

        data_proyek.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel1.setText("DATA PROYEK");

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table1);

        b_detail.setBackground(new java.awt.Color(42, 37, 98));
        b_detail.setText("Detail");
        b_detail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_detailActionPerformed(evt);
            }
        });

        txtcari.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(42, 37, 98)));

        b_cari.setBackground(new java.awt.Color(42, 37, 98));
        b_cari.setText("cari");
        b_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cariActionPerformed(evt);
            }
        });

        b_ajukan.setBackground(new java.awt.Color(42, 37, 98));
        b_ajukan.setText("ajukan");
        b_ajukan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_ajukanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout data_proyekLayout = new javax.swing.GroupLayout(data_proyek);
        data_proyek.setLayout(data_proyekLayout);
        data_proyekLayout.setHorizontalGroup(
            data_proyekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(data_proyekLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(data_proyekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(data_proyekLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(data_proyekLayout.createSequentialGroup()
                        .addGroup(data_proyekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(data_proyekLayout.createSequentialGroup()
                                .addComponent(b_detail, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b_ajukan, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))))
            .addGroup(data_proyekLayout.createSequentialGroup()
                .addComponent(cmbinvestor, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        data_proyekLayout.setVerticalGroup(
            data_proyekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(data_proyekLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(data_proyekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_detail, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_ajukan, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbinvestor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainpane.add(data_proyek, "card2");

        detail_proyek.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel3.setText("DETAIL PROYEK");

        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(table2);

        b_kembali.setBackground(new java.awt.Color(42, 37, 98));
        b_kembali.setText("KEMBALI");
        b_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_kembaliActionPerformed(evt);
            }
        });

        b_step.setBackground(new java.awt.Color(42, 37, 98));
        b_step.setText("detail step");
        b_step.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_stepActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout detail_proyekLayout = new javax.swing.GroupLayout(detail_proyek);
        detail_proyek.setLayout(detail_proyekLayout);
        detail_proyekLayout.setHorizontalGroup(
            detail_proyekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detail_proyekLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(detail_proyekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(detail_proyekLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 707, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(detail_proyekLayout.createSequentialGroup()
                        .addGroup(detail_proyekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(detail_proyekLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(b_step, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(b_kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 504, Short.MAX_VALUE))))
        );
        detail_proyekLayout.setVerticalGroup(
            detail_proyekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detail_proyekLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detail_proyekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_step, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainpane.add(detail_proyek, "card2");

        ajukan.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel2.setText("TAMBAH DANA PERSTEP PROYEK");

        b_tambah.setBackground(new java.awt.Color(42, 37, 98));
        b_tambah.setText("Tambah");
        b_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_tambahActionPerformed(evt);
            }
        });

        b_kembali2.setBackground(new java.awt.Color(42, 37, 98));
        b_kembali2.setText("Kembali");
        b_kembali2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_kembali2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel5.setText("Dana Step Proyek");

        txtstep.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(42, 37, 98)));
        txtstep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstepActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel8.setText("ID Step");

        txtid2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(42, 37, 98)));
        txtid2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtid2ActionPerformed(evt);
            }
        });

        b_update.setBackground(new java.awt.Color(42, 37, 98));
        b_update.setText("Update");
        b_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_updateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ajukanLayout = new javax.swing.GroupLayout(ajukan);
        ajukan.setLayout(ajukanLayout);
        ajukanLayout.setHorizontalGroup(
            ajukanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ajukanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ajukanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ajukanLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel7))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ajukanLayout.createSequentialGroup()
                        .addComponent(b_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(b_update, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_kembali2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ajukanLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(ajukanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtid2, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
                            .addComponent(txtstep)
                            .addGroup(ajukanLayout.createSequentialGroup()
                                .addGroup(ajukanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(17, 17, 17))
        );
        ajukanLayout.setVerticalGroup(
            ajukanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ajukanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ajukanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_kembali2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_update, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtid2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(txtstep, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(176, 176, 176)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainpane.add(ajukan, "card2");

        detail_step.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel4.setText("DETAIL STEP PROYEK");

        table3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table3MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(table3);

        b_keluar.setBackground(new java.awt.Color(42, 37, 98));
        b_keluar.setText("KEMBALI");
        b_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_keluarActionPerformed(evt);
            }
        });

        b_tambah1.setBackground(new java.awt.Color(42, 37, 98));
        b_tambah1.setText("TAMBAH");
        b_tambah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_tambah1ActionPerformed(evt);
            }
        });

        b_ubah.setBackground(new java.awt.Color(42, 37, 98));
        b_ubah.setText("ubah");
        b_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_ubahActionPerformed(evt);
            }
        });

        b_selesai.setBackground(new java.awt.Color(42, 37, 98));
        b_selesai.setText("selesai");
        b_selesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_selesaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout detail_stepLayout = new javax.swing.GroupLayout(detail_step);
        detail_step.setLayout(detail_stepLayout);
        detail_stepLayout.setHorizontalGroup(
            detail_stepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detail_stepLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(detail_stepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(detail_stepLayout.createSequentialGroup()
                        .addComponent(jScrollPane4)
                        .addContainerGap())
                    .addGroup(detail_stepLayout.createSequentialGroup()
                        .addGroup(detail_stepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(detail_stepLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(b_tambah1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b_ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b_selesai, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b_keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 347, Short.MAX_VALUE))))
        );
        detail_stepLayout.setVerticalGroup(
            detail_stepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detail_stepLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detail_stepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_tambah1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_selesai, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainpane.add(detail_step, "card2");

        add(mainpane, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void b_detailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_detailActionPerformed
        mainpane.removeAll();
    mainpane.repaint();
    mainpane.revalidate();

    // Menambahkan panel detail proyek
    mainpane.add(detail_proyek);
    mainpane.repaint();
    mainpane.revalidate();
    
    // Mengambil model tabel dan baris yang dipilih
    DefaultTableModel model = (DefaultTableModel) table1.getModel();
    int row = table1.getSelectedRow();
    
    // Validasi jika baris yang dipilih valid
    if (row >= 0) {
        // Kolom pertama dan kedua
        String id_admin = String.valueOf(table1.getValueAt(row, 1));  // ID Admin
        String id_proyek = String.valueOf(table1.getValueAt(row, 2)); // ID Proyek
        String status = String.valueOf(table1.getValueAt(row, 7));
        // Menyimpan data ke dalam map
        tableDataMap.put(id_admin, id_proyek);
        if(status.equalsIgnoreCase("Disetujui")) {
            b_step.setVisible(true);
        }

        // Perbarui tampilan dengan data terkait
        // Pastikan fungsi ini ada dan memperbarui data sesuai ID Proyek
    }
     datatable2();
// TODO add your handling code here:
    }//GEN-LAST:event_b_detailActionPerformed

    private void b_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cariActionPerformed

 try {
        Statement statement =  conek1.GetConnection().createStatement();
        ResultSet res=statement.executeQuery("select  proyek.id_pelaksana,\n" +
"    proyek.id_admin,\n" +
"    proyek.id,\n" +
"    proyek.nama_proyek,\n" +
"    proyek.lokasi,\n" +
"    proyek.estimasi, sum(total) AS TOTAL, proyek.status from PROYEK  join pelaksana on proyek.id_pelaksana = pelaksana.id_pelaksana  join danaproyek on proyek.id = danaproyek.id_proyek where proyek.nama_proyek like '%" + txtcari.getText() + "%' GROUP BY proyek.id_pelaksana, proyek.id_admin, proyek.id, proyek.nama_proyek, proyek.lokasi, proyek.estimasi, proyek.status; ");
       
        DefaultTableModel tbl = new DefaultTableModel();
          tbl.addColumn("ID PELAKSANA");
   tbl.addColumn("ID ADMIN");
        tbl.addColumn("ID PROYEK");
  
    tbl.addColumn("NAMA PROYEK");
    tbl.addColumn("LOKASI PROYEK");
    tbl.addColumn("ESTIMASI");
    tbl.addColumn("TOTAL DANA");
    tbl.addColumn("STATUS");
        
                table1.setModel(tbl);
                                DecimalFormat df = new DecimalFormat("#,###");

                while(res.next())
            {
                 long totalDana = res.getLong("TOTAL");
                tbl.addRow(new Object[] {
                   res.getString("id_pelaksana"),
                res.getString("id_admin"),
               res.getString("id"),
                res.getString("nama_proyek"),
                res.getString("lokasi"),
                res.getString("estimasi"),
                 df.format(totalDana),
                 res.getString("status")
                   
                });
                 table1.setModel(tbl);
            }
        }catch (Exception e) {
            JOptionPane.showMessageDialog(this,"salah");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_b_cariActionPerformed

    private void b_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_kembaliActionPerformed
        mainpane.removeAll();
        mainpane.repaint();
        mainpane.revalidate();
        
        mainpane.add(data_proyek);
        mainpane.repaint();
        mainpane.revalidate();
        // TODO add your handling code here:
    }//GEN-LAST:event_b_kembaliActionPerformed

    private void table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1MouseClicked
b_detail.setVisible(true);
 b_ajukan.setVisible(true);
 cmbinvestor.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_table1MouseClicked

    private void b_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_tambahActionPerformed
 
    String dana = txtstep.getText();
    
    String id = txtid2.getText();
   
    
     
   

    // Validasi input
    if (id.isEmpty() || dana.isEmpty()  ) {
        JOptionPane.showMessageDialog(null, "Semua field harus diisi dan admin harus dipilih.");
        return;
    }
   

    try {
        // Simpan ke database
        Statement statement = conek1.GetConnection().createStatement();
      String sql = "UPDATE step_proyek SET Dana_perstep = '" + dana + "' Where id_step = '" + id + "';";
              


        statement.executeUpdate(sql);
        statement.close();

        // Notifikasi sukses
       
        JOptionPane.showMessageDialog(null, "Data berhasil disimpan");

        // Kosongkan field input
        
        txtstep.setText("");
       
        txtid2.setText("");
        
 mainpane.removeAll();
        mainpane.repaint();
        mainpane.revalidate();
        
        mainpane.add(detail_step);
        mainpane.repaint();
        mainpane.revalidate();
        // Reset ke pilihan default
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Data gagal disimpan: " + e.getMessage());
    }
     
 
datatable3();
      
    }//GEN-LAST:event_b_tambahActionPerformed

    private void b_kembali2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_kembali2ActionPerformed
mainpane.removeAll();
        mainpane.repaint();
        mainpane.revalidate();
        
        mainpane.add(detail_step);
        mainpane.repaint();
        mainpane.revalidate();
        
        datatable2();          // TODO add your handling code here:
    }//GEN-LAST:event_b_kembali2ActionPerformed

    private void txtid2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtid2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtid2ActionPerformed

    private void txtstepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstepActionPerformed

    private void b_stepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_stepActionPerformed
        mainpane.removeAll();
        mainpane.repaint();
        mainpane.revalidate();
        
        mainpane.add(detail_step);
        mainpane.repaint();
        mainpane.revalidate();
        
        datatable3();
        // TODO add your handling code here:
    }//GEN-LAST:event_b_stepActionPerformed

    private void b_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_keluarActionPerformed
         mainpane.removeAll();
        mainpane.repaint();
        mainpane.revalidate();
        
        mainpane.add(detail_proyek);
        mainpane.repaint();
        mainpane.revalidate();
        // TODO add your handling code here:
    }//GEN-LAST:event_b_keluarActionPerformed

    private void b_tambah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_tambah1ActionPerformed
         int row = table3.getSelectedRow();
    if (row >= 0) {
        // Ambil data dari baris yang dipilih dan set ke dalam form (misalnya textfield)
        String id = (String)table3.getValueAt(row, 1);
         txtid2.setText(String.valueOf(id));
         
          mainpane.removeAll();
        mainpane.repaint();
        mainpane.revalidate();
        
        mainpane.add(ajukan);
        mainpane.repaint();
        mainpane.revalidate();
        
    }else {
        JOptionPane.showMessageDialog(this, "Pilih data yang ingin diubah terlebih dahulu!", "Peringatan", JOptionPane.WARNING_MESSAGE);
    } 
        
        
        datatable3();
        // TODO add your handling code here:
    }//GEN-LAST:event_b_tambah1ActionPerformed

    private void b_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_ubahActionPerformed
       

    // Ambil data baris yang dipilih di tabel
    int row = table3.getSelectedRow();
    if (row >= 0) {
        // Ambil data dari baris yang dipilih dan set ke dalam form (misalnya textfield)
        String id = (String)table3.getValueAt(row, 1);
        String Step = table3.getValueAt(row, 2).toString();  // Misalnya kolom 1 berisi nama
          
          
        // Isi data ke form edit (sesuaikan dengan komponen form Anda)
          txtid2.setText(String.valueOf(id));
        txtstep.setText(String.valueOf(Step));   // Misalnya field untuk ID
         
        
         mainpane.removeAll();
    mainpane.repaint();
    mainpane.revalidate();
    
    mainpane.add(ajukan);
    mainpane.repaint();
    mainpane.revalidate();
    
    // Set tombol yang akan ditampilkan
   b_tambah.setVisible(false);
    b_update.setVisible(true);
          
        // Misalnya field untuk nama
    } else {
        JOptionPane.showMessageDialog(this, "Pilih data yang ingin diubah terlebih dahulu!", "Peringatan", JOptionPane.WARNING_MESSAGE);
    } 
        // TODO add your handling code here:
    }//GEN-LAST:event_b_ubahActionPerformed

    private void b_selesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_selesaiActionPerformed
       DefaultTableModel model = (DefaultTableModel) table3.getModel();
    int row = table3.getSelectedRow();
    
    // Validasi jika baris yang dipilih valid
    if (row >= 0) {
        // Kolom pertama dan kedua
        String idStep = String.valueOf(table3.getValueAt(row, 1));  // ID Admin
        

    try {
        
        // Simpan ke database
        Statement statement = conek1.GetConnection().createStatement();
      String sql = "update  step_proyek SET status = 'Selesai' Where id_step = '" + idStep + "';";


        statement.executeUpdate(sql);
        statement.close();

        // Notifikasi sukses
       
        JOptionPane.showMessageDialog(null, "Step berhasil diselesaikan");

       
 
        // Reset ke pilihan default
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Data gagal disimpan: " + e.getMessage());
    }
    }
    
    
   
 datatable3();
// TODO add your handling code here:
    }//GEN-LAST:event_b_selesaiActionPerformed

    private void table3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table3MouseClicked
        b_ubah.setVisible(true);
        b_selesai.setVisible(true);
        b_keluar.setVisible(true);
        
        
    
    
        // TODO add your handling code here:
    }//GEN-LAST:event_table3MouseClicked

    private void b_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_updateActionPerformed
        String id = txtid2.getText();
String step = txtstep.getText();



   

    try {
        // Query SQL untuk update data
        String query = "UPDATE step_proyek SET  step = '" + step +  "' WHERE ID_step = '" + id+ "';";
        
        // Gunakan Statement untuk menjalankan query
         Statement stmt =conek1.GetConnection().createStatement();
        stmt.executeUpdate(query); 
         JOptionPane.showMessageDialog(null, "Data berhasil diupdate");// Menjalankan query untuk memperbarui data
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error updating data: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }

    // Sembunyikan form setelah update
    b_tambah.setVisible(true);
    b_update.setVisible(false);
    mainpane.removeAll();
    mainpane.add(detail_step);
    mainpane.repaint();
    mainpane.revalidate();
    
    datatable3();
        // TODO add your handling code here:
    }//GEN-LAST:event_b_updateActionPerformed

    private void b_ajukanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_ajukanActionPerformed
 DefaultTableModel model = (DefaultTableModel) table1.getModel();
    int row = table1.getSelectedRow();

    if (row >= 0) {
        String idproyek = (String) table1.getValueAt(row, 2);

        try {
            // Buat koneksi dan statement
            Statement statement = conek1.GetConnection().createStatement();

            // Periksa apakah dana_perstep pada stepproyek kosong
            String queryCheck = "SELECT COUNT(*) AS countEmpty FROM step_proyek WHERE ID_proyek = '" + idproyek + "' AND (Dana_perstep IS NULL OR dana_perstep = '')";
            ResultSet rsCheck = statement.executeQuery(queryCheck);

            if (rsCheck.next() && rsCheck.getInt("countEmpty") > 0) {
                // Jika ada dana_perstep yang kosong
                JOptionPane.showMessageDialog(null, "Data dana_perstep pada stepproyek belum lengkap. Mohon lengkapi sebelum mengajukan.");
                return;
            }

            // Ambil nama inestor
            String investorDipilih = (String) cmbinvestor.getSelectedItem();
            if (investorDipilih.equalsIgnoreCase("- Pilih Investor -") || investorDipilih == null) {
                JOptionPane.showMessageDialog(null, "Pilih Investor terlebih dahulu.");
                return;
            }
            String idinvestor = investor.get(investorDipilih);
            
            // Ambil data perusahaan
            ResultSet rs = statement.executeQuery("SELECT * FROM perusahaan WHERE id_perusahaan = '" + userIdP + "';");
            if (!rs.next()) {
                JOptionPane.showMessageDialog(null, "Data perusahaan tidak ditemukan.");
                return;
            }
            String idPerusahaan = rs.getString("id_perusahaan");
            String namaperusahaan = rs.getString("Nama");

            // Ambil data proyek dari tabel
            String namaproyek = (String) table1.getValueAt(row, 3);
            String lokasiproyek = (String) table1.getValueAt(row, 4);
            String estimasiproyek = (String) table1.getValueAt(row, 5);
            String totaldana = (String) table1.getValueAt(row, 6);

            // Query untuk insert transaksi
            String queryInsert = "INSERT INTO transaksi (nama_perusahaan, nama_proyek, nama_investor, "
                    + "metode_transaksi, lokasi_proyek, estimasi_proyek, total_dana, total_investasi, status_transaksi, tanggal_pengajuan, tanggal_transaksi,"
                    + " ID_investor, ID_proyek, ID_perusahaan) " +
                                 "VALUES ('" + namaperusahaan + "', '" + namaproyek + "', '" + investorDipilih + "', '', '" +
                                 lokasiproyek + "', '" + estimasiproyek + "', '" + totaldana + "','', 'Diajukan', NOW(), null, '" +
                                 idinvestor + "', '" + idproyek + "', '" + idPerusahaan + "');";

            // Eksekusi query insert
            statement.executeUpdate(queryInsert);
            JOptionPane.showMessageDialog(null, "Data berhasil diajukan.");

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat mengajukan data: " + e.getMessage());
        }
    } else {
        JOptionPane.showMessageDialog(null, "Tidak ada baris yang dipilih pada tabel.");
    }
             // TODO add your handling code here:
    }//GEN-LAST:event_b_ajukanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ajukan;
    private rojerusan.RSMaterialButtonRectangle b_ajukan;
    private rojerusan.RSMaterialButtonRectangle b_cari;
    private rojerusan.RSMaterialButtonRectangle b_detail;
    private rojerusan.RSMaterialButtonRectangle b_keluar;
    private rojerusan.RSMaterialButtonRectangle b_kembali;
    private rojerusan.RSMaterialButtonRectangle b_kembali2;
    private rojerusan.RSMaterialButtonRectangle b_selesai;
    private rojerusan.RSMaterialButtonRectangle b_step;
    private rojerusan.RSMaterialButtonRectangle b_tambah;
    private rojerusan.RSMaterialButtonRectangle b_tambah1;
    private rojerusan.RSMaterialButtonRectangle b_ubah;
    private rojerusan.RSMaterialButtonRectangle b_update;
    private javax.swing.JComboBox<String> cmbinvestor;
    private javax.swing.JPanel data_proyek;
    private javax.swing.JPanel detail_proyek;
    private javax.swing.JPanel detail_step;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel mainpane;
    private javax.swing.JTable table1;
    private javax.swing.JTable table2;
    private javax.swing.JTable table3;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txtid2;
    private javax.swing.JTextField txtstep;
    // End of variables declaration//GEN-END:variables

    private void datatable1() {
         
      
    DefaultTableModel tbl = new DefaultTableModel();
    tbl.addColumn("ID PELAKSANA");
    tbl.addColumn("ID ADMIN");
    tbl.addColumn("ID PROYEK");
    tbl.addColumn("NAMA PROYEK");
    tbl.addColumn("LOKASI PROYEK");
    tbl.addColumn("ESTIMASI");
    tbl.addColumn("TOTAL DANA");
    tbl.addColumn("STATUS");

    table1.setModel(tbl);

    try {
        Statement statement = conek1.GetConnection().createStatement();

        // Format angka besar
        DecimalFormat df = new DecimalFormat("#,###");

        ResultSet res = statement.executeQuery(
            "SELECT proyek.id_pelaksana, proyek.id_admin, proyek.id, proyek.nama_proyek, " +
            "proyek.lokasi, proyek.estimasi, SUM(total) AS TOTAL, proyek.status " +
            "FROM PROYEK " +
            "JOIN pelaksana ON proyek.id_pelaksana = pelaksana.id_pelaksana " +
            "JOIN danaproyek ON proyek.id = danaproyek.id_proyek " +
            "WHERE proyek.id_perusahaan = '" + userIdP + "' " +
            "GROUP BY proyek.id_pelaksana, proyek.id_admin, proyek.id, proyek.nama_proyek, proyek.lokasi, proyek.estimasi, proyek.status"
        );

        while (res.next()) {
            tbl.addRow(new Object[]{
                res.getString("id_pelaksana"),
                res.getString("id_admin"),
                res.getString("id"),
                res.getString("nama_proyek"),
                res.getString("lokasi"),
                res.getString("estimasi"),
                df.format(res.getLong("TOTAL")),  // Format angka besar
                res.getString("status")
            });
        }

        res.close();
        statement.close();
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Gagal memuat data: " + e.getMessage());
    }
}
 

   private void datatable2() {
    if (!tableDataMap.isEmpty()) {
        // Mengambil satu ID proyek dari HashMap
        String idProyek = tableDataMap.values().iterator().next();
      
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("ID PROYEK");
        tbl.addColumn("ID DANA");
        tbl.addColumn("DANA");
        tbl.addColumn("TOTAL");

        table2.setModel(tbl);

        try {
            Statement statement = conek1.GetConnection().createStatement();

            // Format angka besar
            DecimalFormat df = new DecimalFormat("#,###");

            String sql = "SELECT * FROM danaproyek WHERE id_proyek = '" + idProyek + "'";
            ResultSet res = statement.executeQuery(sql);

            while (res.next()) {
                
                tbl.addRow(new Object[]{
                    res.getString("id_proyek"),
                    res.getString("id_dana"),
                    res.getString("dana"),  // Format angka besar
                    df.format(res.getLong("total"))  // Format angka besar
                });
            }

            res.close();
            statement.close();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal memuat data: " + e.getMessage());
        }
    }


}

    private void datatable3() {
        if (!tableDataMap.isEmpty()) {
        // Mengambil satu ID proyek dari HashMap
        String idProyek = tableDataMap.values().iterator().next();
        

        // Menyiapkan table model
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("ID PROYEK");
        tbl.addColumn("ID STEP");
        tbl.addColumn("STEP");
        tbl.addColumn("TARGET");
                tbl.addColumn("DANA");

         tbl.addColumn("STATUS");

        // Set table model untuk table2
        table3.setModel(tbl);

        try {
            // Membuat statement dari koneksi
            Statement statement = conek1.GetConnection().createStatement();

            // Menjalankan query untuk mengambil data berdasarkan ID proyek
            String sql = "SELECT * FROM step_proyek WHERE id_proyek = '" + idProyek + "'";
            ResultSet res = statement.executeQuery(sql);

            // Menambahkan data ke dalam table model
            while (res.next()) {
                tbl.addRow(new Object[]{
                     res.getString("id_proyek"),
                    res.getString("id_step"),
                    
                    res.getString("step"),
                    res.getString("target"),
                     res.getString("Dana_perstep"),
                     res.getString("status")
                   
                });
            }

            // Menutup result set dan statement
            res.close();
            statement.close();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal memuat data: " + e.getMessage());
        }  
        } 
    }

    private void hapusDataDariDatabase(String id) {
        String query2 = "DELETE FROM danaproyek WHERE id_proyek = '" + id +  "';";
        String query1 = "DELETE FROM proyek WHERE  id = '" + id +  "';";
        
        try ( Statement stmt =conek1.GetConnection().createStatement();
                ) {
             stmt.executeUpdate(query2);
            stmt.executeUpdate(query1);
           // Eksekusi query untuk menghapus data
        } catch (SQLException e) {
            e.printStackTrace();  // Menampilkan error jika ada masalah
        }
    }

   
  }

