
import Koneksi.conek1;
import java.sql.Connection;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Acer
 */
public class MenuHome1 extends javax.swing.JPanel {

private String userIdi;


    /**
     * Creates new form Dasboard
     */
    public MenuHome1(String userIdi) {
        initComponents();
        
         this.userIdi= userIdi;
         
         
         datatable1();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSMaterialButtonRectangle1 = new rojerusan.RSMaterialButtonRectangle();
        mainPane = new javax.swing.JPanel();
        pn_dana = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        rSMaterialButtonRectangle2 = new rojerusan.RSMaterialButtonRectangle();

        rSMaterialButtonRectangle1.setText("rSMaterialButtonRectangle1");

        setBorder(javax.swing.BorderFactory.createMatteBorder(0, 3, 0, 0, new java.awt.Color(42, 37, 98)));
        setLayout(new java.awt.CardLayout());

        mainPane.setBackground(new java.awt.Color(255, 255, 255));
        mainPane.setLayout(new java.awt.CardLayout());

        pn_dana.setBackground(new java.awt.Color(255, 255, 255));

        table1.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table1.setSelectionBackground(new java.awt.Color(255, 255, 255));
        table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table1);

        jTextField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(42, 37, 98)));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel1.setText("DATA PENGAJUAN DANA");

        rSMaterialButtonRectangle2.setBackground(new java.awt.Color(42, 37, 98));
        rSMaterialButtonRectangle2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        rSMaterialButtonRectangle2.setText("Cari");
        rSMaterialButtonRectangle2.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        rSMaterialButtonRectangle2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangle2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_danaLayout = new javax.swing.GroupLayout(pn_dana);
        pn_dana.setLayout(pn_danaLayout);
        pn_danaLayout.setHorizontalGroup(
            pn_danaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_danaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pn_danaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_danaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_danaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rSMaterialButtonRectangle2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE))
                .addContainerGap())
        );
        pn_danaLayout.setVerticalGroup(
            pn_danaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_danaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(pn_danaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_danaLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pn_danaLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(rSMaterialButtonRectangle2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        mainPane.add(pn_dana, "card2");

        add(mainPane, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void rSMaterialButtonRectangle2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSMaterialButtonRectangle2ActionPerformed

    private void table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1MouseClicked
       
        // TODO add your handling code here:
    }//GEN-LAST:event_table1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel mainPane;
    private javax.swing.JPanel pn_dana;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle1;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle2;
    private javax.swing.JTable table1;
    // End of variables declaration//GEN-END:variables

    private void datatable1() {
        

      DefaultTableModel tbl = new DefaultTableModel();
tbl.addColumn("NAMA PERUSAHAAN");
tbl.addColumn("ID PROYEK");
tbl.addColumn("NAMA PROYEK");
tbl.addColumn("NAMA INVESTOR");
tbl.addColumn("METODE TRANSAKSI");
tbl.addColumn("LOKASI PROYEK");
tbl.addColumn("ESTIMASI");
tbl.addColumn("DANA PROYEK");
tbl.addColumn("JUMLAH INVESTASI");

tbl.addColumn("TANGGAL PENGAJUAN");
tbl.addColumn("TANGGAL TRANSAKSI");
tbl.addColumn("TAHAP");


tbl.addColumn("STATUS PENGAJUAN");

table1.setModel(tbl);

try {
     Connection conn = conek1.GetConnection();
    Statement statement = conn.createStatement();
    // Validasi input userIdP untuk mencegah SQL injection
    if (userIdi == null || userIdi.isEmpty()) {
        throw new IllegalArgumentException("ID Investor tidak valid");
    }

    // Jalankan query SQL
    ResultSet res = statement.executeQuery(
        "SELECT * FROM transaksi WHERE ID_investor = '" + userIdi+ "';"
    );

    // Ambil hasil query dan tambahkan ke tabel
    while (res.next()) {
        tbl.addRow(new Object[]{
            res.getString("nama_perusahaan"),
            res.getString("ID_proyek"),
            res.getString("nama_proyek"),
            res.getString("nama_investor"),
            res.getString("metode_transaksi"),
            res.getString("lokasi_proyek"),
            res.getString("estimasi_proyek"),
            res.getString("total_dana"),
             res.getString("total_investasi"),
            res.getString("tanggal_pengajuan"),
            res.getString("tanggal_transaksi"),
                        res.getString("pencairan_tahap"),

            res.getString("status_transaksi")
        });
    }

    res.close();
    statement.close();
} catch (SQLException e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(this, "Gagal memuat data: " + e.getMessage());
} catch (IllegalArgumentException e) {
    JOptionPane.showMessageDialog(this, e.getMessage());
}   }

  
}
