
import java.sql.Statement;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import Koneksi.conek1;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Acer
 */
public class MenuPelaksana extends javax.swing.JPanel {
private String username;
private String userId;
private String userIdP;

 private HashMap<String, String> adminMap = new HashMap<>();
 
     
    public MenuPelaksana(String username,  String userId, String userIdP) {
        initComponents();
        this.username = username;
        this.userId = userId;
         this.userIdP = userIdP;
       
        
        b_hapus.setVisible(false);
        b_batal.setVisible(false);
        b_ubah.setVisible(false);
        b_tambah.setVisible(true);
        loadAdmin();
       datatable();
    }
    
    private void loadAdmin() {
          try {
            // Membuat statement dari koneksi
            Statement stmt = conek1.GetConnection().createStatement();
            
            // Query untuk mendapatkan ID dan nama admin
            String sql = "SELECT id_admin, Nama FROM admin_pelaksana where id_perusahaan = '" + userIdP +"';" ;
            ResultSet rs = stmt.executeQuery(sql);
            
            // Tambahkan pilihan default ke dropdown
            cmbAdmin.addItem("- Pilih Admin -");
            
            // Tambahkan admin ke dropdown dan HashMap
            while (rs.next()) {
                String idAdmin = rs.getString("id_admin"); // ID bertipe String
                String namaAdmin = rs.getString("Nama");
                cmbAdmin.addItem(namaAdmin);         // Tambahkan nama admin ke dropdown
                adminMap.put(namaAdmin, idAdmin);
                
            }
             cmbAdmin.repaint();
            // Menutup statement
            stmt.close();
           
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal terhubung ke database: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainpane = new javax.swing.JPanel();
        Data_proyek = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        b_cari = new rojerusan.RSMaterialButtonRectangle();
        b_tambah = new rojerusan.RSMaterialButtonRectangle();
        txtcari = new javax.swing.JTextField();
        b_hapus = new rojerusan.RSMaterialButtonRectangle();
        b_batal = new rojerusan.RSMaterialButtonRectangle();
        b_ubah = new rojerusan.RSMaterialButtonRectangle();
        buat_proyek = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        b_simpan = new rojerusan.RSMaterialButtonRectangle();
        b_keluar = new rojerusan.RSMaterialButtonRectangle();
        jLabel3 = new javax.swing.JLabel();
        txtlokasiproyek = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtnamaproyek = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtestimasi = new javax.swing.JTextField();
        b_update = new rojerusan.RSMaterialButtonRectangle();
        jLabel6 = new javax.swing.JLabel();
        txtkodeproyek = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cmbAdmin = new javax.swing.JComboBox<>();

        setBorder(javax.swing.BorderFactory.createMatteBorder(0, 3, 0, 0, new java.awt.Color(42, 37, 98)));
        setLayout(new java.awt.CardLayout());

        mainpane.setBackground(new java.awt.Color(255, 255, 255));
        mainpane.setLayout(new java.awt.CardLayout());

        Data_proyek.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel1.setText("DATA PROYEK");

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table1.setGridColor(new java.awt.Color(0, 0, 255));
        table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table1);

        b_cari.setBackground(new java.awt.Color(42, 37, 98));
        b_cari.setText("CARI");
        b_cari.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        b_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cariActionPerformed(evt);
            }
        });

        b_tambah.setBackground(new java.awt.Color(42, 37, 98));
        b_tambah.setText("TAMBAH");
        b_tambah.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        b_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_tambahActionPerformed(evt);
            }
        });

        txtcari.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(42, 37, 98)));
        txtcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcariActionPerformed(evt);
            }
        });

        b_hapus.setBackground(new java.awt.Color(42, 37, 98));
        b_hapus.setText("Hapus");
        b_hapus.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        b_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_hapusActionPerformed(evt);
            }
        });

        b_batal.setBackground(new java.awt.Color(42, 37, 98));
        b_batal.setText("batal");
        b_batal.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        b_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_batalActionPerformed(evt);
            }
        });

        b_ubah.setBackground(new java.awt.Color(42, 37, 98));
        b_ubah.setText("Ubah");
        b_ubah.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        b_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_ubahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Data_proyekLayout = new javax.swing.GroupLayout(Data_proyek);
        Data_proyek.setLayout(Data_proyekLayout);
        Data_proyekLayout.setHorizontalGroup(
            Data_proyekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Data_proyekLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(Data_proyekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                    .addGroup(Data_proyekLayout.createSequentialGroup()
                        .addGroup(Data_proyekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(b_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(b_ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(b_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        Data_proyekLayout.setVerticalGroup(
            Data_proyekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Data_proyekLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Data_proyekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );

        mainpane.add(Data_proyek, "card2");

        buat_proyek.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel2.setText("BUAT PROYEK");

        b_simpan.setBackground(new java.awt.Color(42, 37, 98));
        b_simpan.setText("simpan");
        b_simpan.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        b_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_simpanActionPerformed(evt);
            }
        });

        b_keluar.setBackground(new java.awt.Color(42, 37, 98));
        b_keluar.setText("keluar");
        b_keluar.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        b_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_keluarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel3.setText("NAMA PROYEK");

        txtlokasiproyek.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(42, 37, 98)));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel4.setText("LOKASI PROYEK");

        txtnamaproyek.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(42, 37, 98)));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel5.setText("ESTIMASI PENGERJAAN");

        txtestimasi.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(42, 37, 98)));

        b_update.setBackground(new java.awt.Color(42, 37, 98));
        b_update.setText("update");
        b_update.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        b_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_updateActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel6.setText("KODE PROYEK");

        txtkodeproyek.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(42, 37, 98)));

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel8.setText("PILIH ADMIN");

        javax.swing.GroupLayout buat_proyekLayout = new javax.swing.GroupLayout(buat_proyek);
        buat_proyek.setLayout(buat_proyekLayout);
        buat_proyekLayout.setHorizontalGroup(
            buat_proyekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buat_proyekLayout.createSequentialGroup()
                .addGroup(buat_proyekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, buat_proyekLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, buat_proyekLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(buat_proyekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtestimasi, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
                            .addComponent(txtlokasiproyek)
                            .addComponent(txtnamaproyek, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
                            .addComponent(txtkodeproyek, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
                            .addGroup(buat_proyekLayout.createSequentialGroup()
                                .addGroup(buat_proyekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addGroup(buat_proyekLayout.createSequentialGroup()
                                        .addComponent(b_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(b_update, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(b_keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel6))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(cmbAdmin, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(17, 17, 17))
        );
        buat_proyekLayout.setVerticalGroup(
            buat_proyekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buat_proyekLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(buat_proyekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_update, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtkodeproyek, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtnamaproyek, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtlokasiproyek, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtestimasi, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        mainpane.add(buat_proyek, "card2");

        add(mainpane, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void b_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cariActionPerformed
 try {
        Statement statement =  conek1.GetConnection().createStatement();
        ResultSet res=statement.executeQuery("select * from proyek where username = '" + username + "' AND nama_proyek like '%" + txtcari.getText() +  "%';" );
        DefaultTableModel tbl = new DefaultTableModel();
          tbl.addColumn("ID PELAKSANA");
   tbl.addColumn("ID ADMIN");
        tbl.addColumn("ID PROYEK");
  
    tbl.addColumn("NAMA PROYEK");
    tbl.addColumn("LOKASI PROYEK");
    tbl.addColumn("ESTIMASI");
    tbl.addColumn("STATUS");
        
                table1.setModel(tbl);
                
                while(res.next())
            {
                tbl.addRow(new Object[] {
                   res.getString("id_pelaksana"),
                res.getString("id_admin"),
               res.getString("id"),
                res.getString("nama_proyek"),
                res.getString("lokasi"),
                res.getString("estimasi"),
                 res.getString("status")
                   
                });
                 table1.setModel(tbl);
            }
        }catch (Exception e) {
            JOptionPane.showMessageDialog(this,"salah");
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_b_cariActionPerformed

    private void b_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_tambahActionPerformed
        mainpane.removeAll();
        mainpane.repaint();
        mainpane.revalidate();
        
        mainpane.add(buat_proyek);
        mainpane.repaint();
        mainpane.revalidate();
        b_update.setVisible(false);
         b_simpan.setVisible(true);
      
        
// TODO add your handling code here:
    }//GEN-LAST:event_b_tambahActionPerformed

    private void b_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_simpanActionPerformed
        String nama = txtnamaproyek.getText();
    String lokasi = txtlokasiproyek.getText();
    String estimasi = txtestimasi.getText();
    String kode = txtkodeproyek.getText();
     

   
    
    
    // Ambil admin yang dipilih dari JComboBox
    String adminDipilih = (String) cmbAdmin.getSelectedItem(); // Nama admin
    String idAdmin = adminMap.get(adminDipilih);               // Ambil ID admin dari HashMap

    // Validasi input
    if (nama.isEmpty() || lokasi.isEmpty() || estimasi.isEmpty() || kode.isEmpty() || adminDipilih == null ) {
        JOptionPane.showMessageDialog(null, "Semua field harus diisi dan admin harus dipilih.");
        return;
    }

    try {
        // Simpan ke database
        Statement statement = conek1.GetConnection().createStatement();
      String sql = "INSERT INTO proyek (id, username, nama_proyek, lokasi, estimasi, status, id_pelaksana, "
              + "id_admin, id_manajer, id_perusahaan) VALUES ('" 
            + kode + "', '" 
            + username + "', '" 
            + nama + "', '" 
            + lokasi + "', '" 
            + estimasi + "', '','" 
            + userId + "','" 
            + idAdmin + "', NULL , '"+ userIdP + "')";


        statement.executeUpdate(sql);
        statement.close();

        // Notifikasi sukses
       
        JOptionPane.showMessageDialog(null, "Data berhasil disimpan");

        // Kosongkan field input
        txtnamaproyek.setText("");
        txtlokasiproyek.setText("");
        txtestimasi.setText("");
        txtkodeproyek.setText("");
        cmbAdmin.setSelectedIndex(0); 
 cmbAdmin.removeAllItems();
 
    loadAdmin();
        // Reset ke pilihan default
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Data gagal disimpan: " + e.getMessage());
    }

    datatable();
        
       
    



        
        datatable();
        // TODO add your handling code here:
    }//GEN-LAST:event_b_simpanActionPerformed

    private void b_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_keluarActionPerformed
          mainpane.removeAll();
        mainpane.repaint();
        mainpane.revalidate();
        
        mainpane.add(Data_proyek);
        mainpane.repaint();
        mainpane.revalidate();
        
        datatable();
        // TODO add your handling code here:
    }//GEN-LAST:event_b_keluarActionPerformed

    private void txtcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcariActionPerformed

    private void table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1MouseClicked

        b_hapus.setVisible(true);
            b_batal.setVisible(true);
                       b_ubah.setVisible(true);

// TODO add your handling code here:
    }//GEN-LAST:event_table1MouseClicked

    private void b_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_hapusActionPerformed
        int row = table1.getSelectedRow();  // Mengambil indeks baris yang dipilih
    if (row >= 0) {
        // Tampilkan konfirmasi sebelum menghapus
        int confirm = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin menghapus data ini?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            // Mendapatkan ID yang terkait dengan baris yang dipilih
            String id = (String) table1.getValueAt(row, 2);  // Misalnya ID berada di kolom pertama (indeks 0)

            // Menghapus data dari tabel (model tabel)
            DefaultTableModel model = (DefaultTableModel) table1.getModel();
            model.removeRow(row);  // Menghapus baris yang dipilih dari model

            // Menghapus data dari database
            hapusDataDariDatabase(id);

            // Atur ulang tampilan tombol setelah penghapusan
           
            b_hapus.setVisible(false); // Sembunyikan tombol hapus
            b_batal.setVisible(false); 
             b_ubah.setVisible(false); 
// Sembunyikan tombol batal
        }
    } else {
        JOptionPane.showMessageDialog(this, "Pilih data yang ingin dihapus terlebih dahulu!", "Peringatan", JOptionPane.WARNING_MESSAGE);
    }

        // TODO add your handling code here:
    }//GEN-LAST:event_b_hapusActionPerformed

    private void b_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_batalActionPerformed
       
        b_hapus.setVisible(false);
            b_batal.setVisible(false);
           b_ubah.setVisible(false);
           
        // TODO add your handling code here:
    }//GEN-LAST:event_b_batalActionPerformed

    private void b_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_updateActionPerformed
  String namaproyek = txtnamaproyek.getText();
String lokasiproyek = txtlokasiproyek.getText();
String estimasi = txtestimasi.getText();// Ambil nama baru dari text field
  // Ambil ID dari text field (dari data yang dipilih sebelumnya)

    // Perbarui data di database
     String adminDipilih = (String) cmbAdmin.getSelectedItem(); // Nama admin
    String idAdmin = adminMap.get(adminDipilih); 
   

    // Perbarui data di tabel
    DefaultTableModel model = (DefaultTableModel) table1.getModel();
    int row = table1.getSelectedRow();
    if (row >= 0) {
         String id = (String)table1.getValueAt(row, 2);
         model.setValueAt(idAdmin, row, 1);
       model.setValueAt(namaproyek, row, 3);  // Perbarui nama proyek di kolom 1
        model.setValueAt(lokasiproyek, row, 4); // Perbarui lokasi proyek di kolom 2
        model.setValueAt(estimasi, row, 5);
        
 updateDataInDatabase(id, namaproyek, lokasiproyek, estimasi);// Perbarui nama di kolom 1
    }

    // Sembunyikan form setelah update
    b_simpan.setVisible(true);
    b_update.setVisible(false);
    mainpane.removeAll();
    mainpane.add(Data_proyek);
    mainpane.repaint();
    mainpane.revalidate();

        // TODO add your handling code here:
    }//GEN-LAST:event_b_updateActionPerformed

    private void b_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_ubahActionPerformed
          mainpane.removeAll();
    mainpane.repaint();
    mainpane.revalidate();
    
    mainpane.add(buat_proyek);
    mainpane.repaint();
    mainpane.revalidate();
    
    // Set tombol yang akan ditampilkan
    b_simpan.setVisible(false);
    b_update.setVisible(true);

    // Ambil data baris yang dipilih di tabel
    int row = table1.getSelectedRow();
    if (row >= 0) {
        // Ambil data dari baris yang dipilih dan set ke dalam form (misalnya textfield)
        String id = (String)table1.getValueAt(row, 2);
        String namaProyek = table1.getValueAt(row, 3).toString();  // Misalnya kolom 1 berisi nama
          String lokasiproyek = table1.getValueAt(row, 4).toString();
           String estimasi = table1.getValueAt(row, 5).toString();
        // Isi data ke form edit (sesuaikan dengan komponen form Anda)
          txtkodeproyek.setText(String.valueOf(id));
        txtnamaproyek.setText(String.valueOf(namaProyek));   // Misalnya field untuk ID
        txtlokasiproyek.setText(lokasiproyek); 
        txtestimasi.setText(estimasi);
        // Misalnya field untuk nama
    } else {
        JOptionPane.showMessageDialog(this, "Pilih data yang ingin diubah terlebih dahulu!", "Peringatan", JOptionPane.WARNING_MESSAGE);
    }

        // TODO add your handling code here:
    }//GEN-LAST:event_b_ubahActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Data_proyek;
    private rojerusan.RSMaterialButtonRectangle b_batal;
    private rojerusan.RSMaterialButtonRectangle b_cari;
    private rojerusan.RSMaterialButtonRectangle b_hapus;
    private rojerusan.RSMaterialButtonRectangle b_keluar;
    private rojerusan.RSMaterialButtonRectangle b_simpan;
    private rojerusan.RSMaterialButtonRectangle b_tambah;
    private rojerusan.RSMaterialButtonRectangle b_ubah;
    private rojerusan.RSMaterialButtonRectangle b_update;
    private javax.swing.JPanel buat_proyek;
    private javax.swing.JComboBox<String> cmbAdmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainpane;
    private javax.swing.JTable table1;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txtestimasi;
    private javax.swing.JTextField txtkodeproyek;
    private javax.swing.JTextField txtlokasiproyek;
    private javax.swing.JTextField txtnamaproyek;
    // End of variables declaration//GEN-END:variables

    private void datatable() {
        DefaultTableModel tbl = new DefaultTableModel();
  tbl.addColumn("ID PELAKSANA");
   tbl.addColumn("ID ADMIN");
        tbl.addColumn("ID PROYEK");
  
    tbl.addColumn("NAMA PROYEK");
    tbl.addColumn("LOKASI PROYEK");
    tbl.addColumn("ESTIMASI");
    tbl.addColumn("STATUS");
   
   
    table1.setModel(tbl);
    
    try {
        Statement statement =conek1.GetConnection().createStatement();
        ResultSet res = statement.executeQuery("select * from PROYEK join pelaksana on proyek.id_pelaksana "
                + "= pelaksana.id_pelaksana where proyek.username = '" + username + "'; ");
        
        while (res.next()) {
            tbl.addRow(new Object[]{
                res.getString("id_pelaksana"),
                res.getString("id_admin"),
               res.getString("id"),
                res.getString("nama_proyek"),
                res.getString("lokasi"),
                res.getString("estimasi"),
                 res.getString("status")
                 
                    
               
            });
        }
    } catch (Exception e) {
        e.printStackTrace(); 
          JOptionPane.showMessageDialog(this, "Gagal memuat data: " + e.getMessage());  
       
    }
    }

   

    private void hapusDataDariDatabase(String id) {
        String query = "DELETE FROM proyek WHERE  id = '" + id + "' AND username = '" + username + "';";
        try ( Statement stmt =conek1.GetConnection().createStatement();
                ) {
            stmt.executeUpdate(query);  // Eksekusi query untuk menghapus data
        } catch (SQLException e) {
            e.printStackTrace();  // Menampilkan error jika ada masalah
        }
    }

    

    private void updateDataInDatabase(String id, String namaproyek, String lokasiproyek, String estimasi) {
          try {
        // Query SQL untuk update data
        String query = "UPDATE proyek SET nama_proyek = '" + namaproyek + "', lokasi = '" + lokasiproyek +
                "', estimasi = '" + estimasi + "' WHERE ID = '" + id+ "';";
        
        // Gunakan Statement untuk menjalankan query
         Statement stmt =conek1.GetConnection().createStatement();
        stmt.executeUpdate(query);  // Menjalankan query untuk memperbarui data
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error updating data: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }
}
